// Hardcoded placeholder data for the pre-integration phase.
// Everything the UI renders comes from this file; real fetching goes here later.

export const PROFILE = {
  id: "00000000-0000-0000-0000-000000000000",
  telegram_id: 12345,
  username: "devmode",
  first_name: "Issav",
  last_name: "Mode",
  photo_url: "",
  current_streak: 12,
  longest_streak: 15,
  last_read_date: "2026-09-23",
  total_quiz_correct: 42,
  total_quiz_answered: 50,
};

export const TOTAL_DAYS = 182;
export const CURRENT_DAY = 42;

export const TODAY_GROUPS = [
  {
    id: "rp-42",
    day_number: 42,
    book: "Numbers",
    chapters: "4-6",
    chapterLabels: ["Numbers 4", "Numbers 5", "Numbers 6"],
  },
];

export const COMPLETED_CHAPTERS = ["Numbers 4"];

export const QUIZ_QUESTIONS = [
  {
    id: "q-1",
    chapter_label: "Numbers 4",
    question_text: "Which tribe was set apart to carry the tabernacle?",
    option_a: "Levi",
    option_b: "Judah",
    option_c: "Benjamin",
    option_d: "Reuben",
    correct_option: "a",
  },
  {
    id: "q-2",
    chapter_label: "Numbers 5",
    question_text: "What was the test for a wife suspected of unfaithfulness?",
    option_a: "Bitter water",
    option_b: "A burnt offering",
    option_c: "Casting lots",
    option_d: "A seven-day fast",
    correct_option: "a",
  },
  {
    id: "q-3",
    chapter_label: "Numbers 6",
    question_text: "How many years did the Israelites wander in the wilderness?",
    option_a: "10",
    option_b: "40",
    option_c: "7",
    option_d: "12",
    correct_option: "b",
  },
];

// Sorted by score descending; contains PROFILE so "(You)" and rank render.
export const LEADERBOARD = [
  {
    id: "u-1",
    telegram_id: 100025,
    username: "sandrawilson",
    first_name: "Sandra",
    last_name: "Wilson",
    photo_url: null,
    current_streak: 19,
    longest_streak: 24,
    total_quiz_correct: 44,
    total_quiz_answered: 69,
    score: 96,
  },
  {
    id: "u-2",
    telegram_id: 100030,
    username: "thomasjones",
    first_name: "Thomas",
    last_name: "Jones",
    photo_url: null,
    current_streak: 13,
    longest_streak: 21,
    total_quiz_correct: 39,
    total_quiz_answered: 66,
    score: 88,
  },
  {
    id: "u-3",
    telegram_id: 100019,
    username: "nancyanderson",
    first_name: "Nancy",
    last_name: "Anderson",
    photo_url: null,
    current_streak: 10,
    longest_streak: 12,
    total_quiz_correct: 33,
    total_quiz_answered: 63,
    score: 74,
  },
  {
    id: PROFILE.id,
    telegram_id: PROFILE.telegram_id,
    username: PROFILE.username,
    first_name: PROFILE.first_name,
    last_name: PROFILE.last_name,
    photo_url: PROFILE.photo_url,
    current_streak: PROFILE.current_streak,
    longest_streak: PROFILE.longest_streak,
    total_quiz_correct: PROFILE.total_quiz_correct,
    total_quiz_answered: PROFILE.total_quiz_answered,
    score: 71,
  },
  {
    id: "u-4",
    telegram_id: 100023,
    username: "lindajones",
    first_name: "Linda",
    last_name: "Jones",
    photo_url: null,
    current_streak: 11,
    longest_streak: 13,
    total_quiz_correct: 26,
    total_quiz_answered: 52,
    score: 63,
  },
  {
    id: "u-5",
    telegram_id: 100007,
    username: "jamesbrown",
    first_name: "James",
    last_name: "Brown",
    photo_url: null,
    current_streak: 6,
    longest_streak: 9,
    total_quiz_correct: 21,
    total_quiz_answered: 44,
    score: 58,
  },
  {
    id: "u-6",
    telegram_id: 100044,
    username: "mariagarcia",
    first_name: "Maria",
    last_name: "Garcia",
    photo_url: null,
    current_streak: 4,
    longest_streak: 8,
    total_quiz_correct: 17,
    total_quiz_answered: 38,
    score: 47,
  },
  {
    id: "u-7",
    telegram_id: 100051,
    username: "peterdavis",
    first_name: "Peter",
    last_name: "Davis",
    photo_url: null,
    current_streak: 2,
    longest_streak: 5,
    total_quiz_correct: 12,
    total_quiz_answered: 30,
    score: 39,
  },
];
